create or replace TRIGGER TGR_TIPO_PROVEEDOR
BEFORE INSERT ON TIPO_PROVEEDOR
FOR EACH ROW
 WHEN (new.ID_TIPO_PROVEEDOR IS NULL or new.ID_TIPO_PROVEEDOR = 0) 
BEGIN
  SELECT seq_tipo_proveedor.NEXTVAL
  INTO :new.ID_TIPO_PROVEEDOR
  FROM dual;
END;