//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public BOLETA()
        {
            this.DETALLE_BOLETA = new HashSet<DETALLE_BOLETA>();
        }
    
        public int ID_BOLETA { get; set; }
        public Nullable<decimal> VALOR_DESC_BOLETA { get; set; }
        public long VALOR_TOTAL_BOLETA { get; set; }
        public System.DateTime FECHA_EMISION_BOLETA { get; set; }
        public int RUT_HUESPED { get; set; }
        public int RUT_EMPLEADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual HUESPED HUESPED { get; set; }
        public virtual ICollection<DETALLE_BOLETA> DETALLE_BOLETA { get; set; }
    }
}
