//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.DETALLE_HABITACION = new HashSet<DETALLE_HABITACION>();
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
            this.FACTURA = new HashSet<FACTURA>();
            this.HABITACION = new HashSet<HABITACION>();
            this.HUESPED = new HashSet<HUESPED>();
            this.ORDEN_COMPRA = new HashSet<ORDEN_COMPRA>();
        }
    
        public int RUT_CLIENTE { get; set; }
        public string DV_CLIENTE { get; set; }
        public string DIRECCION_CLIENTE { get; set; }
        public string CORREO_CLIENTE { get; set; }
        public Nullable<long> TELEFONO_CLIENTE { get; set; }
        public short ID_COMUNA { get; set; }
        public short ID_USUARIO { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public short ID_GIRO { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<DETALLE_HABITACION> DETALLE_HABITACION { get; set; }
        public virtual GIRO GIRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<HABITACION> HABITACION { get; set; }
        public virtual ICollection<HUESPED> HUESPED { get; set; }
        public virtual ICollection<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
    }
}
