//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ACCESORIOS
    {
        public short ID_DETALLE_ACCESORIO { get; set; }
        public short ID_ACCESORIO { get; set; }
        public short NUMERO_HABITACION { get; set; }
        public short CANTIDAD { get; set; }
    
        public virtual ACCESORIO ACCESORIO { get; set; }
        public virtual HABITACION HABITACION { get; set; }
    }
}
