//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int ID_DETALLE_FACTURA { get; set; }
        public string DESCRIPCION_DETALLE { get; set; }
        public int CANTIDAD { get; set; }
        public long VALOR_TOTAL { get; set; }
        public int ID_FACTURA { get; set; }
        public int VALOR_UNITARIO { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
    }
}
