//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_HABITACION
    {
        public short ID_DETALLE_H { get; set; }
        public short NUMERO_HABITACION { get; set; }
        public int RUT_CLIENTE { get; set; }
        public int RUT_HUESPED { get; set; }
        public short ID_PENSION { get; set; }
        public System.DateTime FECHA_LLEGADA { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public short NUMERO_ORDEN { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
        public virtual HABITACION HABITACION { get; set; }
        public virtual HUESPED HUESPED { get; set; }
        public virtual PENSION PENSION { get; set; }
    }
}
