//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.FACTURA = new HashSet<FACTURA>();
            this.ORDEN_COMPRA = new HashSet<ORDEN_COMPRA>();
            this.PEDIDO = new HashSet<PEDIDO>();
            this.RECEPCION = new HashSet<RECEPCION>();
        }
    
        public int RUT_EMPLEADO { get; set; }
        public string DV_EMPLEADO { get; set; }
        public string PNOMBRE_EMPLEADO { get; set; }
        public string SNOMBRE_EMPLEADO { get; set; }
        public string APP_PATERNO_EMPLEADO { get; set; }
        public string APP_MATERNO_EMPLEADO { get; set; }
        public short ID_USUARIO { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual ICollection<RECEPCION> RECEPCION { get; set; }
    }
}
