//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HostalEntities : DbContext
    {
        public HostalEntities()
            : base("name=HostalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCESORIO> ACCESORIO { get; set; }
        public DbSet<BOLETA> BOLETA { get; set; }
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<DETALLE_ACCESORIOS> DETALLE_ACCESORIOS { get; set; }
        public DbSet<DETALLE_BOLETA> DETALLE_BOLETA { get; set; }
        public DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public DbSet<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
        public DbSet<DETALLE_PLATOS> DETALLE_PLATOS { get; set; }
        public DbSet<DETALLE_RECEPCION> DETALLE_RECEPCION { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<FAMILIA> FAMILIA { get; set; }
        public DbSet<HABITACION> HABITACION { get; set; }
        public DbSet<HUESPED> HUESPED { get; set; }
        public DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<PEDIDO> PEDIDO { get; set; }
        public DbSet<PENSION> PENSION { get; set; }
        public DbSet<PLATO> PLATO { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECEPCION> RECEPCION { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<TIPO_HABITACION> TIPO_HABITACION { get; set; }
        public DbSet<TIPO_PLATO> TIPO_PLATO { get; set; }
        public DbSet<TIPO_PROVEEDOR> TIPO_PROVEEDOR { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
    }
}
