//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUESPED
    {
        public HUESPED()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.DETALLE_ORDEN = new HashSet<DETALLE_ORDEN>();
            this.DETALLE_PASAJEROS = new HashSet<DETALLE_PASAJEROS>();
        }
    
        public int RUT_HUESPED { get; set; }
        public string DV_HUESPED { get; set; }
        public string PNOMBRE_HUESPED { get; set; }
        public string SNOMBRE_HUESPED { get; set; }
        public string APP_PATERNO_HUESPED { get; set; }
        public string APP_MATERNO_HUESPED { get; set; }
        public Nullable<long> TELEFONO_HUESPED { get; set; }
        public string REGISTRADO { get; set; }
        public int RUT_CLIENTE { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
        public virtual ICollection<DETALLE_PASAJEROS> DETALLE_PASAJEROS { get; set; }
    }
}
