//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENSION
    {
        public PENSION()
        {
            this.DETALLE_ORDEN = new HashSet<DETALLE_ORDEN>();
            this.DETALLE_PASAJEROS = new HashSet<DETALLE_PASAJEROS>();
            this.DETALLE_PLATOS = new HashSet<DETALLE_PLATOS>();
        }
    
        public short ID_PENSION { get; set; }
        public string NOMBRE_PENSION { get; set; }
        public int VALOR_PENSION { get; set; }
    
        public virtual ICollection<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
        public virtual ICollection<DETALLE_PASAJEROS> DETALLE_PASAJEROS { get; set; }
        public virtual ICollection<DETALLE_PLATOS> DETALLE_PLATOS { get; set; }
    }
}
