//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLE_PEDIDO = new HashSet<DETALLE_PEDIDO>();
            this.DETALLE_RECEPCION = new HashSet<DETALLE_RECEPCION>();
        }
    
        public long ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public DateTime? FECHA_VENCIMIENTO_PRODUCTO { get; set; }
        public short STOCK_PRODUCTO { get; set; }
        public short STOCK_CRITICO_PRODUCTO { get; set; }
        public string DESCRIPCION_PRODUCTO { get; set; }
        public int PRECIO_PRODUCTO { get; set; }
        public short ID_FAMILIA { get; set; }
        public int RUT_PROVEEDOR { get; set; }
        public short ID_PRODUCTO_SEQ { get; set; }

        public string NombreYPrecio
        {
            get { return this.NOMBRE_PRODUCTO + " $" + this.PRECIO_PRODUCTO; }
        }

        public virtual ICollection<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
        public virtual ICollection<DETALLE_RECEPCION> DETALLE_RECEPCION { get; set; }
        public virtual FAMILIA FAMILIA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
