//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION
    {
        public RECEPCION()
        {
            this.DETALLE_RECEPCION = new HashSet<DETALLE_RECEPCION>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public short NUMERO_RECEPCION { get; set; }
        public System.DateTime FECHA_RECEPCION { get; set; }
        public int RUT_PROVEEDOR { get; set; }
        public int RUT_EMPLEADO { get; set; }
    
        public virtual ICollection<DETALLE_RECEPCION> DETALLE_RECEPCION { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
