//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_HABITACION
    {
        public TIPO_HABITACION()
        {
            this.HABITACION = new HashSet<HABITACION>();
        }
    
        public short ID_TIPO_HABITACION { get; set; }
        public string NOMBRE_TIPO_HABITACION { get; set; }
        public short CANTIDAD_PASAJERO { get; set; }
        public int PRECIO_TIPO { get; set; }
    
        public virtual ICollection<HABITACION> HABITACION { get; set; }
    }
}
