//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CLIENTE_FRECUENTE
    {
        public string RUT { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string GIRO { get; set; }
        public Nullable<decimal> CANTIDAD_ORDENES { get; set; }
    }
}
